name: Send WhatsApp Reminder

on:
  schedule:
    - cron: '0 4 * * *' # 07:00 Ελλάδας (UTC+3)
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send WhatsApp via CallMeBot
        run: |
          curl "https://api.callmebot.com/whatsapp.php?phone=+306932377969&text=Καλημέρα! Η ημερήσια αναφορά είναι έτοιμη εδώ: https://btsonbtson.github.io/NewsBrief/&apikey=7338852"
